
[general]
	#The material blacklist of this module.
	materialBlacklist = ["platinum", "zinc", "bismuth", "uranium", "osmium", "tungsten", "iron", "gold", "copper", "tin", "silver", "lead", "nickel"]

