
[client]
	contributorEffect = ""
	#Tooltips require pressing shift to be shown
	tooltipRequiresShift = false
	#Max line width shown in description of tooltips
	#Range: > 50
	tooltipWrapWidth = 100
	#Show item tags and nbt in advanced tooltips
	debugTooltip = true
	#Allowed values: vanilla, kiwi
	debugTooltipNBTFormatter = "vanilla"

