#Saturation value:
#Range: 0 ~ 10
pumpkin_soup_saturation = 1
#Saturation value:
#Range: 0 ~ 10
energy_drink_saturation = 1
#Hunger value:
#Range: 0 ~ 30
melon_pie_hunger = 7
#Saturation value:
#Range: 0 ~ 10
apple_pie_saturation = 1
#Hunger value:
#Range: 0 ~ 30
pumpkin_soup_hunger = 7
#Hunger value:
#Range: 0 ~ 30
energyBar_hunger = 12
#Saturation value:
#Range: 0 ~ 10
berry_pie_saturation = 1
#Saturation value:
#Range: 0 ~ 10
superFoodBar_saturation = 2
#Saturation value:
#Range: 0 ~ 10
superFoodShake_saturation = 1
#Hunger value:
#Range: 0 ~ 30
superFoodBar_hunger = 12
#Hunger value:
#Range: 0 ~ 30
apple_pie_hunger = 7
#Hunger value:
#Range: 0 ~ 30
energy_drink_hunger = 9
#Hunger value:
#Range: 0 ~ 30
superFoodShake_hunger = 10
#Saturation value:
#Range: 0 ~ 10
melon_pie_saturation = 1
#Saturation value:
#Range: 0 ~ 10
energyBar_saturation = 2
#Hunger value:
#Range: 0 ~ 30
berry_pie_hunger = 7

