
#Client-only settings
[client]
	#Show Entity Actives Potions on Overlay ?
	showEntityActivesPotions = false
	#Show stats like Hearts and Armor in Minimal View ?
	showMinimalStats = false
	#Only use 'TOP_LEFT' or 'BOTTOM_LEFT' positions. ('TOP_RIGHT' and 'BOTTOM_RIGHT' W.I.P) 
	#Allowed Values: TOP_LEFT, TOP_RIGHT, BOTTOM_LEFT, BOTTOM_RIGHT
	overlayPosition = "BOTTOM_LEFT"
	#Show Particles on Hit or Heal Entity ?
	showParticles = true
	#Show Entity Name On Overlay ?
	showEntityNameInOverlay = false
	#Show InGame Damage Indicator Overlay ?
	showInGameOverlay = false
	#Define the size of H.U.D when pointing entity
	#Range: 0.0 ~ 10.0
	hudScale = 1.0
	#Show Entity Stats On Overlay ?
	showEntityStatsInOverlay = false
	#Display huge or little potion effect icons
	showPotionInfo = false

