
#Basalt Generation
[basalt]
	#Maximal height for basalt pocket generation [0-255, default: 40]
	#Range: 0 ~ 255
	basaltMaxHeight = 40
	#Size of basalt pockets [0-100, default: 33]
	#Range: 0 ~ 100
	basaltSize = 33
	#Generate basalt in the world [true / false]
	basaltGeneration = false
	#Minimal height for basalt pocket generation, [0-255, default: 0]
	#Range: 0 ~ 255
	basaltMinHeight = 5
	#Chances of basalt pocket being generated [0-100, default: 10]
	#Range: 0 ~ 100
	basaltChance = 10

#Slate Generation
[slate]
	#Maximal height for slate pocket generation [0-255, default: 70]
	#Range: 0 ~ 255
	slateMaxHeight = 40
	#Chances of slate pocket being generated [0-100, default: 10]
	#Range: 0 ~ 100
	slateChance = 10
	#Size of slate pockets [0-100, default: 33]
	#Range: 0 ~ 100
	slateSize = 33
	#Generate slate in the world [true / false]
	slateGeneration = false
	#Minimal height for slate pocket generation, [0-255, default: 40]
	#Range: 0 ~ 255
	slateMinHeight = 45

#Marble Generation
[marble]
	#Size of marble pockets [0-100, default: 20]
	#Range: 0 ~ 100
	marbleSize = 20
	#Chances of marble pocket being generated [0-100, default: 10]
	#Range: 0 ~ 100
	marbleChance = 10
	#Generate marble in the world [true / false]
	marbleGeneration = false
	#Maximal height for marble pocket generation [0-255, default: 100]
	#Range: 0 ~ 255
	marbleMaxHeight = 120
	#Minimal height for marble pocket generation, [0-255, default: 50]
	#Range: 0 ~ 255
	marbleMinHeight = 60

#Gneiss Generation
[gneiss]
	#Chances of gneiss pocket being generated [0-100, default: 10]
	#Range: 0 ~ 100
	gneissChance = 40
	#Minimal height for gneiss pocket generation, [0-255, default: 50]
	#Range: 0 ~ 255
	gneissMinHeight = 35
	#Generate gneiss in the world [true / false]
	gneissGeneration = false
	#Maximal height for gneiss pocket generation [0-255, default: 100]
	#Range: 0 ~ 255
	gneissMaxHeight = 65
	#Size of gneiss pockets [0-100, default: 33]
	#Range: 0 ~ 100
	gneissSize = 33

#Jade Generation
[jade]
	#Chances of jade pocket being generated [0-100, default: 5]
	#Range: 0 ~ 100
	jadeChance = 1
	#Maximal height for jade pocket generation [0-255, default: 100]
	#Range: 0 ~ 255
	jadeMaxHeight = 120
	#Generate jade in the world [true / false]
	jadeGeneration = false
	#Minimal height for jade pocket generation, [0-255, default: 50]
	#Range: 0 ~ 255
	jadeMinHeight = 50
	#Size of jade pockets [0-100, default: 15]
	#Range: 0 ~ 100
	jadeSize = 1

#Larvikite Generation
[larvikite]
	#Chances of larvikite pocket being generated [0-100, default: 5]
	#Range: 0 ~ 100
	larvikiteChance = 1
	#Minimal height for larvikite pocket generation, [0-255, default: 50]
	#Range: 0 ~ 255
	larvikiteMinHeight = 32
	#Generate larvikite in the world [true / false]
	larvikiteGeneration = false
	#Size of larvikite pockets [0-100, default: 15]
	#Range: 0 ~ 100
	larvikiteSize = 20
	#Maximal height for larvikite pocket generation [0-255, default: 100]
	#Range: 0 ~ 255
	larvikiteMaxHeight = 72

